### ISSUE TITLE
[install script] tests are failing

### ISSUE THREAD

**Issue by 130s** [130s/hut_10sqft#169]
https://github.com/130s/hut_10sqft/pull/166#issuecomment-320080612

**Comment by 130s** [comment]
No idea why this [fails on Travis](https://travis-ci.org/130s/hut_10sqft/jobs/264231122#L3253),
```
+ls -al /home/travis/link/Current
lrwxrwxrwx 1 travis travis 78 Aug 14 04:05 /home/travis/link/Current -> /home/travis/Periodic/GooglePhotos/2017/
+mkdir -p '/home/travis/data/Dropbox/Camera Uploads/' '/home/travis/data/Dropbox/SharedFromOthers/Camera Uploads from Mio' /home/travis/link/Current/08
mkdir: cannot create directory ‘/home/travis/link/Current’: File exists
+cd '/home/travis/data/Dropbox/SharedFromOthers/Camera Uploads from Mio'
```

while it works fine on local Trusty:
```
$ mkdir -p /tmp/link
$ cd /tmp/link
$ ln -sf ~/Periodic/GooglePhotos/2017 Current
$ cd ..
$ mkdir -p aa bb link/Current/"${TARGET_FOLDER}"
$ ll link/Current/08
$ ll link/
total 12K
drwxrwxr-x 2 n130s n130s 4.0K Aug 13 21:08 ./
lrwxrwxrwx 1 n130s n130s   76 Aug 13 21:08 Current -> /home/n130s/Periodic/GooglePhotos/2017/
drwxrwxr-x 5 n130s n130s 4.0K Aug 13 21:08 ../
```

**Comment by 130s** [comment]
Locally was able to confirm; This error happens when symlink exists but the target of it does not exist (GooglePhonyo dir in the example below doesn't exist).
```
n130s@tork-kudu1:/tmp/hut_test/link$ ls
Current
n130s@tork-kudu1:/tmp/hut_test/link$ rm Current
n130s@tork-kudu1:/tmp/hut_test/link$ ln -sf ~/Periodic/GooglePhonyo/2017 Current
n130s@tork-kudu1:/tmp/hut_test/link$ ll
total 12K
drwxrwxr-x 2 n130s n130s 4.0K Aug 13 21:20 ./
lrwxrwxrwx 1 n130s n130s   76 Aug 13 21:20 Current -> /home/n130s/Periodic/GooglePhonyo/2017
drwxrwxr-x 5 n130s n130s 4.0K Aug 13 21:08 ../
n130s@tork-kudu1:/tmp/hut_test/link$ cd ..
n130s@tork-kudu1:/tmp/hut_test$ mkdir -p aa bb link/Current/09
mkdir: cannot create directory ‘link/Current’: File exists
```

**Comment by 130s** [comment]
https://github.com/130s/hut_10sqft/issues/169#issue-247907103 is resolved (by https://github.com/130s/hut_10sqft/commit/5bb5b2e5c07fd9d5a878bfb98886c0194f25dae7).

Now a new issue: https://travis-ci.org/130s/hut_10sqft/jobs/264235749#L6721
```
Util.find_all_files with unlimited depth specified. ... Before removing dir /tmp/proovingground_of_mad_overlord: ['prooving2.txt', 'package1.xml', 'depth1']
Current dir: /home/travis/build/130s/hut_10sqft/test
After copying files into /tmp/proovingground_of_mad_overlord: ['prooving2.txt', 'package1.xml', 'depth1']
Current dir: /tmp/proovingground_of_mad_overlord
when depth_max=0: Search path: ., abspath: /tmp/proovingground_of_mad_overlord
Depth_max: 0 num of found files: 3
list_expected: ['/tmp/proovingground_of_mad_overlord/package1.xml', '/tmp/proovingground_of_mad_overlord/prooving3.xml']
FAIL
tearDown: chdir-ed to /home/travis/build/130s/hut_10sqft/test
======================================================================
FAIL: Util.find_all_files with unlimited depth specified.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/130s/hut_10sqft/test/test_util.py", line 138, in test_find_all_files_unlimiteddepth
    self._test_find_all_files_filepattern(depthmax=0, expected_files_relat=expected_files)
  File "/home/travis/build/130s/hut_10sqft/test/test_util.py", line 127, in _test_find_all_files_filepattern
    self.assertEqual(common_list, list_expected)
AssertionError: Lists differ: ['/tmp/proovingground_of_mad_o... != ['/tmp/proovingground_of_mad_o...
```
