### ISSUE TITLE
[kudu1] meld not starting 

### ISSUE THREAD

**Issue by 130s** [130s/hut_10sqft#178]
```
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-uzmUUclMNf: Connection refused
```

**Comment by 130s** [comment]
From non-tmux terminal it works.

**Comment by 130s** [comment]
```
$ meld . &                                        
[1] 21246
$
(meld:21246): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Failed to connect to socket /tmp/dbus-uzmUUclMNf: Connection refused

(meld:21246): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Failed to connect to socket /tmp/dbus-uzmUUclMNf: Connection refused
Traceback (most recent call last):
  File "/usr/bin/meld", line 178, in <module>
    main()
  File "/usr/bin/meld", line 164, in main
    already_running, dbus_app = meld.dbus_service.setup(app)
  File "/usr/lib/meld/meld/dbus_service.py", line 56, in setup
    bus = dbus.SessionBus()
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-uzmUUclMNf: Connection refused
```

**Comment by 130s** [comment]
- After rebooting OS, the issue is gone.
- This seems to be happening before https://github.com/130s/hut_10sqft/issues/55

**Comment by 130s** [comment]
The following single command [from this answer](https://askubuntu.com/a/514379/24203) solved for me (just running it without doing anything else):
```
$ eval `dbus-launch`
```

**Comment by snth** [comment]
Thank you @130s!
