### ISSUE TITLE
Set up OpenHAB environment on rpi2

### ISSUE THREAD

**Issue by 130s** [130s/hut_10sqft#330]
Following https://github.com/130s/hut_10sqft/issues/268

----

Some tasks taken from https://github.com/130s/hut_10sqft/issues/100#issue-198267746
- [x] Run basic functionality of OpenHAB -> https://github.com/130s/hut_10sqft/issues/330#issuecomment-459996649

**Comment by 130s** [comment]
Using https://github.com/openhab/openhab-snap, it seems failing:
```
uo130s@localhost:~$  sudo snap install openhab
error: cannot perform the following tasks:
- Download snap "openhab" (174) from channel "stable" (write /var/lib/snapd/snaps/openhab_174.snap.partial: structure needs cleaning)
uo130s@localhost:~$ 
```

**Comment by 130s** [comment]
After a few times of rebooting the OS, I now got a different error:
```
$ sudo snap install openhab
error: cannot communicate with server: Post http://localhost/v2/snaps/openhab: EOF
```

**Comment by 130s** [comment]
```
sudo journalctl -u snapd.service
:
Jan 02 08:47:25 localhost.localdomain snapd[1562]: goroutine 5 [running]:                 
Jan 02 08:47:25 localhost.localdomain snapd[1562]: panic(0xe8ee00, 0x119340a8)            
Jan 02 08:47:25 localhost.localdomain snapd[1562]:         /usr/lib/go-1.6/src/runtime/pancf
Jan 02 08:47:25 localhost.localdomain snapd[1562]: github.com/snapcore/snapd/logger.Panicf(0x109f3a8, 0x37, 0x1152ebc4, 0x3, 0x3)
Jan 02 08:47:25 localhost.localdomain snapd[1562]:         /build/snapd-22JIGV/snapd-2.33.1/_build/src/github.com/snapcore/snapd/logger/logger.go:67 +0x14c
Jan 02 08:47:25 localhost.localdomain snapd[1562]: github.com/snapcore/snapd/overlord/state.(*State).Unlock(0x116e0100)                                    
Jan 02 08:47:25 localhost.localdomain snapd[1562]:         /build/snapd-22JIGV/snapd-2.33.1/_build/src/github.com/snapcore/snapd/overlord/state/state.go:235 +0x310
Jan 02 08:47:25 localhost.localdomain snapd[1562]: github.com/snapcore/snapd/overlord/snapstate.(*autoRefresh).Ensure(0x1173aa50, 0x0, 0x0)                        
Jan 02 08:47:25 localhost.localdomain snapd[1562]:         /build/snapd-22JIGV/snapd-2.33.1/_build/src/github.com/snapcore/snapd/overlord/snapstate/autorefresh.go:299 +0xee0
Jan 02 08:47:25 localhost.localdomain snapd[1562]: github.com/snapcore/snapd/overlord/snapstate.(*SnapManager).Ensure(0x1173aa80, 0x0, 0x0)
Jan 02 08:47:25 localhost.localdomain snapd[1562]:         /build/snapd-22JIGV/snapd-2.33.1/_build/src/github.com/snapcore/snapd/overlord/snapstate/snapmgr.go:540 +0xa4
Jan 02 08:47:25 localhost.localdomain snapd[1562]: github.com/snapcore/snapd/overlord.(*StateEngine).Ensure(0x11737540, 0x0, 0x0)                                       
Jan 02 08:47:25 localhost.localdomain snapd[1562]:         /build/snapd-22JIGV/snapd-2.33.1/_build/src/github.com/snapcore/snapd/overlord/stateengine.go:99 +0x194      
Jan 02 08:47:25 localhost.localdomain snapd[1562]: github.com/snapcore/snapd/overlord.(*Overlord).Loop.func1(0x0, 0x0)                                                  
Jan 02 08:47:25 localhost.localdomain snapd[1562]:         /build/snapd-22JIGV/snapd-2.33.1/_build/src/github.com/snapcore/snapd/overlord/overlord.go:262 +0x48         
Jan 02 08:47:25 localhost.localdomain snapd[1562]: github.com/snapcore/snapd/vendor/gopkg.in/tomb%2ev2.(*Tomb).run(0x1150c150, 0x118301b0)                              
Jan 02 08:47:25 localhost.localdomain snapd[1562]:         /build/snapd-22JIGV/snapd-2.33.1/_build/src/github.com/snapcore/snapd/vendor/gopkg.in/tomb.v2/tomb.go:163 +0x1c
Jan 02 08:47:25 localhost.localdomain snapd[1562]: created by github.com/snapcore/snapd/vendor/gopkg.in/tomb%2ev2.(*Tomb).Go
Jan 02 08:47:25 localhost.localdomain snapd[1562]:         /build/snapd-22JIGV/snapd-2.33.1/_build/src/github.com/snapcore/snapd/vendor/gopkg.in/tomb.v2/tomb.go:159 +0x134
Jan 02 08:47:25 localhost.localdomain systemd[1]: snapd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 02 08:47:25 localhost.localdomain systemd[1]: snapd.service: Unit entered failed state.                                
Jan 02 08:47:25 localhost.localdomain systemd[1]: snapd.service: Failed with result 'exit-code'.                           
Jan 02 08:47:26 localhost.localdomain systemd[1]: snapd.service: Service hold-off time over, scheduling restart.           
Jan 02 08:47:26 localhost.localdomain systemd[1]: Stopped Snappy daemon.                                                   
Jan 02 08:47:26 localhost.localdomain systemd[1]: Starting Snappy daemon...                                                
Jan 02 08:47:26 localhost.localdomain snapd[1587]: AppArmor status: apparmor is enabled and all features are available     
Jan 02 08:47:26 localhost.localdomain snapd[1587]: 2019/01/02 08:47:26.700976 daemon.go:343: started snapd/2.33.1 (series 16) ubuntu-core/16 (armhf) linux/4.4.0-1092-raspi2.
Jan 02 08:47:26 localhost.localdomain systemd[1]: Started Snappy daemon.                  
Jan 02 08:47:28 localhost.localdomain snapd[1587]: 2019/01/02 08:47:28.952405 storehelpers.go:413: cannot refresh snap "pi2": snap has no updates available 
```

**Comment by 130s** [comment]
I'm getting to convinced that the board I'm using is RPi3 (this [kit from Sparkfun](https://www.sparkfun.com/products/14644)) but the [image might be RPi2 specific](https://github.com/130s/hut_10sqft/issues/327#issuecomment-450788397). Will wipe out and try RPi3 image.

**Comment by 130s** [comment]
I think the Pi device I've been stuck with is RPi2 ([this kit from Sparkfun](https://www.sparkfun.com/products/13724). The one inhttps://github.com/130s/hut_10sqft/issues/330#issuecomment-451702395 is not the one I'm using for this ticket I suppose).

**Comment by 130s** [comment]
Asked on [snapcraft about `Ubuntu Core` community](https://forum.snapcraft.io/t/snap-install-x-ends-up-with-error-cannot-communicate-with-server-post-http-localhost-v2-snaps-x-eof/9320).

**Comment by 130s** [comment]
Not sure btw if https://github.com/openhab/openhab-snap/issues/8 is related.

**Comment by 130s** [comment]
Using a branch new SD card, Ubuntu Core seems to be working much smoothly https://github.com/130s/hut_10sqft/issues/332#issuecomment-457936501, and `openhab` seems to have been installed.
```
uo130s@localhost:~$ sudo snap install openhab
openhab 2.0.0 from openHAB Foundation e.V. (openhab) installed
```

**Comment by 130s** [comment]
- [ ] Z-wave connectivity via Razberry with other Z-wave devices
- [ ] Controlling Z-wave devices via Z-Way panel.
- [ ] Controlling Z-Wave devices via OpenHAB Z-Wave binding.

**Comment by 130s** [comment]
Tasks taken from https://github.com/130s/hut_10sqft/issues/100#issue-198267746
- [ ] Z-wave connectivity via Razberry with other Z-wave devices
- [ ] Controlling Z-wave devices via Z-Way panel.
- [ ] Controlling Z-Wave devices via OpenHAB Z-Wave binding.

**Comment by 130s** [comment]
Upstream [latest is 2.4](https://www.openhab.org/blog/2018-12-17-openhab-2-4-release.html) while Snap is still 2.0 https://github.com/openhab/openhab-distro/issues/542. Decided to source build.
```
$ sudo snap info openhab 
name:      openhab
summary:   openHAB smart home server
publisher: openHAB Foundation e.V. (openhab)
contact:   snaps@canonical.com
license:   unset
description: |
  openHAB - a vendor and technology agnostic open source automation software for your home.
commands:
  - openhab.clean
  - openhab.client
  - openhab.debug
  - openhab.help
  - openhab.start
  - openhab.status
  - openhab.stop
services:
  openhab: simple, enabled, active
snap-id:      WpdPxW72JupkC8XTgaJsig3LEHdrR56x
tracking:     stable
refresh-date: today at 08:44 UTC
channels:
  stable:    2.0.0          2017-11-14 (174) 101MB -
  candidate: 2.1.0          2017-11-11 (212) 138MB -
  beta:      2.2.0-SNAPSHOT 2017-11-09 (201) 147MB -
  edge:      2.2.0-SNAPSHOT 2017-11-09 (201) 147MB -
installed:   2.0.0                     (174) 101MB -
```

**Comment by 130s** [comment]
Looks like multiple options are available for setting openHAB, not just source build necessarily ([2.4 release note](https://github.com/openhab/openhab-distro/wiki/openHAB-2.4-Release-Notes)). But maybe source build is the only option for Ubuntu Core?
- openHABian -> looks like SD card image solution.
- apt, yum are not available on snap I think.

**Comment by 130s** [comment]
On `Ubuntu Core`, sounds like `apt` is basically not available https://askubuntu.com/questions/902905/install-applications-in-ubuntu-core/925505#925505

[Developer mode](https://developer.ubuntu.com/core/get-started/developer-setup), which can be enabled by installing a classic" snap, allows `apt`. [Someone said](https://askubuntu.com/questions/1011254/what-if-the-snap-i-want-is-not-available-and-i-cant-use-apt#comment1638903_1011303) it's too restrictive with `chroot` being required. I have a feeling this is not the road I want to go down.

So, will try source install. Source install openHAB on linux https://www.openhab.org/docs/installation/linux.html#manual-installation

**Comment by 130s** [comment]
```
$ sudo adduser --system --no-create-home --group --disabled-login openhab
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_PAPER = "en_US.UTF-8",
	LC_ADDRESS = "en_US.UTF-8",
	LC_MONETARY = "en_US.UTF-8",
	LC_NUMERIC = "en_US.UTF-8",
	LC_TELEPHONE = "en_US.UTF-8",
	LC_IDENTIFICATION = "en_US.UTF-8",
	LC_MEASUREMENT = "en_US.UTF-8",
	LC_TIME = "en_US.UTF-8",
	LC_NAME = "en_US.UTF-8",
	LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").
Adding system user `openhab' (UID 111) ...
Adding new group `openhab' (GID 112) ...
groupadd: cannot lock /etc/group; try again later.
adduser: `/usr/sbin/groupadd -g 112 openhab' returned error code 10. Exiting.
```

[Using `--extrausers` is suggested](https://askubuntu.com/questions/871957/how-do-i-create-an-additional-user-on-ubuntu-core) but it didn't work smoothly. Now I'm afraid user db might be corrupted.

```
$ sudo adduser --system --no-create-home --group --disabled-login --extrausers openhab

uo130s@localhost:/var/log$ sudo adduser --extrausers openhab 
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_PAPER = "en_US.UTF-8",
	LC_ADDRESS = "en_US.UTF-8",
	LC_MONETARY = "en_US.UTF-8",
	LC_NUMERIC = "en_US.UTF-8",
	LC_TELEPHONE = "en_US.UTF-8",
	LC_IDENTIFICATION = "en_US.UTF-8",
	LC_MEASUREMENT = "en_US.UTF-8",
	LC_TIME = "en_US.UTF-8",
	LC_NAME = "en_US.UTF-8",
	LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").
Adding user `openhab' ...
Adding new group `openhab' (1001) ...
ENTER EXTRAUSERS_GROUP_FILEEXIT EXTRAUSERS_GROUP_FILEENTER EXTRAUSERS_SHADOWGROUP_FILEEXIT EXTRAUSERS_SHADOWGROUP_FILEAdding new user `openhab' (1001) with group `openhab' ...
Creating home directory `/home/openhab' ...
Copying files from `/etc/skel' ...
Enter new UNIX password: 
Retype new UNIX password: 
No password supplied
Enter new UNIX password: 
Retype new UNIX password: 
No password supplied
Enter new UNIX password: 
Retype new UNIX password: 
No password supplied
passwd: Authentication token manipulation error
passwd: password unchanged
Try again? [y/N] 
Changing the user information for openhab
Enter the new value, or press ENTER for the default
	Full Name []: ^Cadduser: `/usr/bin/chfn --extrausers openhab' exited from signal 2. Exiting.
uo130s@localhost:/var/log$ sudo adduser --system --no-create-home --disabled-login --extrausers openhab 
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_PAPER = "en_US.UTF-8",
	LC_ADDRESS = "en_US.UTF-8",
	LC_MONETARY = "en_US.UTF-8",
	LC_NUMERIC = "en_US.UTF-8",
	LC_TELEPHONE = "en_US.UTF-8",
	LC_IDENTIFICATION = "en_US.UTF-8",
	LC_MEASUREMENT = "en_US.UTF-8",
	LC_TIME = "en_US.UTF-8",
	LC_NAME = "en_US.UTF-8",
	LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").
adduser: The user `openhab' already exists. Exiting.
```
I'm not comfortable moving forward with this. Decided to give it a try on `openHABian`.

**Comment by 130s** [comment]
It's been awhile and I'm no longer sure what is left to do for this ticket, but:

> I'm not comfortable moving forward with this. Decided to give it a try on `openHABian`.

Looks like the RPi3 is running on it with `apt` package. Seems like it's been running reliably for 8 months. Closing.
```
n130s@openHABianPi:~ $ apt-cache policy openhab2
openhab2:
  Installed: 2.4.0-1
  Candidate: 2.4.0-1
  Version table:
 *** 2.4.0-1 500
        500 https://dl.bintray.com/openhab/apt-repo2 stable/main armhf Packages
        100 /var/lib/dpkg/status
     2.3.0-1 500
        500 https://dl.bintray.com/openhab/apt-repo2 stable/main armhf Packages
     2.2.0-1 500
        500 https://dl.bintray.com/openhab/apt-repo2 stable/main armhf Packages
     2.1.0-1 500
        500 https://dl.bintray.com/openhab/apt-repo2 stable/main armhf Packages
     2.0.0-1 500
        500 https://dl.bintray.com/openhab/apt-repo2 stable/main armhf Packages
```
