### ISSUE TITLE
Run 2019 tutorial

### ISSUE THREAD

**Issue by 130s** [130s/hut_10sqft#356]
Confirm [2019/tutorials/installation](https://bitbucket.org/osrf/ariac/wiki/2019/tutorials/installation).

**Comment by 130s** [comment]
Didn't have time to run https://github.com/130s/hut_10sqft/issues/349 first...

**Comment by 130s** [comment]
Failed:

```
root@e05969ab530c:~/catkin_ws# roslaunch osrf_gear sample_environment.launch no_gui:=true
... logging to /root/.ros/log/f3e0332a-4e17-11e9-aa44-0242ac110002/roslaunch-e05969ab530c-2015.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://e05969ab530c:40383/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
  * /rosversion: 1.14.3

NODES
  /
      ariac_sim (osrf_gear/gear.py)

ROS_MASTER_URI=http://localhost:11311

process[ariac_sim-1]: started with pid [2030]
writing file /tmp/ariac/arm1.urdf.xacro
writing file /tmp/ariac/arm2.urdf.xacro
writing file /tmp/ariac/gear.world
writing file /tmp/ariac/gear.launch
writing file /tmp/ariac/gear.urdf.xacro
Running command: roslaunch /tmp/ariac/gear.launch world_path:=/tmp/ariac/gear.world gear_urdf_xacro:=/tmp/ariac/gear.urdf.xacro arm_urdf_dir:=/tmp/ariac/ gui:=false
... logging to /root/.ros/log/f3e0332a-4e17-11e9-aa44-0242ac110002/roslaunch-e05969ab530c-2033.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
xacro: in-order processing became default in ROS Melodic. You can drop the option.
xacro: in-order processing became default in ROS Melodic. You can drop the option.
started roslaunch server http://e05969ab530c:45663/

SUMMARY
========

PARAMETERS
 * /ariac/arm1/arm/action_monitor_rate: 10
  * /ariac/arm1/arm/constraints/elbow_joint/goal: 0.1
   * /ariac/arm1/arm/constraints/elbow_joint/trajectory: 0.1
    * /ariac/arm1/arm/constraints/goal_time: 0.6
     * /ariac/arm1/arm/constraints/linear_arm_actuator_joint/goal: 0.1
      * /ariac/arm1/arm/constraints/linear_arm_actuator_joint/trajectory: 0.1
       * /ariac/arm1/arm/constraints/shoulder_lift_joint/goal: 0.1
        * /ariac/arm1/arm/constraints/shoulder_lift_joint/trajectory: 0.1
 * /ariac/arm1/arm/constraints/shoulder_pan_joint/goal: 0.1
  * /ariac/arm1/arm/constraints/shoulder_pan_joint/trajectory: 0.1
   * /ariac/arm1/arm/constraints/stopped_velocity_tolerance: 0.05
    * /ariac/arm1/arm/constraints/wrist_1_joint/goal: 0.1
     * /ariac/arm1/arm/constraints/wrist_1_joint/trajectory: 0.1
      * /ariac/arm1/arm/constraints/wrist_2_joint/goal: 0.1
       * /ariac/arm1/arm/constraints/wrist_2_joint/trajectory: 0.1
        * /ariac/arm1/arm/constraints/wrist_3_joint/goal: 0.1
 * /ariac/arm1/arm/constraints/wrist_3_joint/trajectory: 0.1
  * /ariac/arm1/arm/gains/elbow_joint/d: 150
   * /ariac/arm1/arm/gains/elbow_joint/i: 1
    * /ariac/arm1/arm/gains/elbow_joint/i_clamp: 25
     * /ariac/arm1/arm/gains/elbow_joint/p: 50000
      * /ariac/arm1/arm/gains/linear_arm_actuator_joint/d: 500
       * /ariac/arm1/arm/gains/linear_arm_actuator_joint/i: 0
        * /ariac/arm1/arm/gains/linear_arm_actuator_joint/i_clamp: 1
 * /ariac/arm1/arm/gains/linear_arm_actuator_joint/p: 10000
  * /ariac/arm1/arm/gains/shoulder_lift_joint/d: 150
   * /ariac/arm1/arm/gains/shoulder_lift_joint/i: 10
    * /ariac/arm1/arm/gains/shoulder_lift_joint/i_clamp: 50
     * /ariac/arm1/arm/gains/shoulder_lift_joint/p: 50000
      * /ariac/arm1/arm/gains/shoulder_pan_joint/d: 150
       * /ariac/arm1/arm/gains/shoulder_pan_joint/i: 0
        * /ariac/arm1/arm/gains/shoulder_pan_joint/i_clamp: 1
 * /ariac/arm1/arm/gains/shoulder_pan_joint/p: 10000
  * /ariac/arm1/arm/gains/wrist_1_joint/d: 5
   * /ariac/arm1/arm/gains/wrist_1_joint/i: 0
    * /ariac/arm1/arm/gains/wrist_1_joint/i_clamp: 1
     * /ariac/arm1/arm/gains/wrist_1_joint/p: 100
      * /ariac/arm1/arm/gains/wrist_2_joint/d: 2
       * /ariac/arm1/arm/gains/wrist_2_joint/i: 0
        * /ariac/arm1/arm/gains/wrist_2_joint/i_clamp: 1
 * /ariac/arm1/arm/gains/wrist_2_joint/p: 75
  * /ariac/arm1/arm/gains/wrist_3_joint/d: 1
   * /ariac/arm1/arm/gains/wrist_3_joint/i: 0
    * /ariac/arm1/arm/gains/wrist_3_joint/i_clamp: 1
     * /ariac/arm1/arm/gains/wrist_3_joint/p: 25
      * /ariac/arm1/arm/joints: ['linear_arm_actu...
       * /ariac/arm1/arm/state_publish_rate: 25
        * /ariac/arm1/arm/stop_trajectory_duration: 0.5
 * /ariac/arm1/arm/type: effort_controller...
  * /ariac/arm1/joint_state_controller/extra_joints: [{'position': 0.0...
   * /ariac/arm1/joint_state_controller/publish_rate: 50
    * /ariac/arm1/joint_state_controller/type: joint_state_contr...
     * /ariac/arm1/robot_description: <?xml version="1....
 * /ariac/arm1/robot_state_publisher/publish_frequency: 50.0
 * /ariac/arm1/robot_state_publisher/tf_prefix:
 * /ariac/arm1/tf_relay/frames: ['linear_arm_actu...
 * /ariac/arm1/tf_relay/prefix: arm1_
 * /ariac/arm2/arm/action_monitor_rate: 10
 * /ariac/arm2/arm/constraints/elbow_joint/goal: 0.1
 * /ariac/arm2/arm/constraints/elbow_joint/trajectory: 0.1
 * /ariac/arm2/arm/constraints/goal_time: 0.6
 * /ariac/arm2/arm/constraints/linear_arm_actuator_joint/goal: 0.1
 * /ariac/arm2/arm/constraints/linear_arm_actuator_joint/trajectory: 0.1
 * /ariac/arm2/arm/constraints/shoulder_lift_joint/goal: 0.1
 * /ariac/arm2/arm/constraints/shoulder_lift_joint/trajectory: 0.1
 * /ariac/arm2/arm/constraints/shoulder_pan_joint/goal: 0.1
 * /ariac/arm2/arm/constraints/shoulder_pan_joint/trajectory: 0.1
 * /ariac/arm2/arm/constraints/stopped_velocity_tolerance: 0.05
 * /ariac/arm2/arm/constraints/wrist_1_joint/goal: 0.1
 * /ariac/arm2/arm/constraints/wrist_1_joint/trajectory: 0.1
 * /ariac/arm2/arm/constraints/wrist_2_joint/goal: 0.1
 * /ariac/arm2/arm/constraints/wrist_2_joint/trajectory: 0.1
 * /ariac/arm2/arm/constraints/wrist_3_joint/goal: 0.1
 * /ariac/arm2/arm/constraints/wrist_3_joint/trajectory: 0.1
 * /ariac/arm2/arm/gains/elbow_joint/d: 150
 * /ariac/arm2/arm/gains/elbow_joint/i: 1
 * /ariac/arm2/arm/gains/elbow_joint/i_clamp: 25
 * /ariac/arm2/arm/gains/elbow_joint/p: 50000
 * /ariac/arm2/arm/gains/linear_arm_actuator_joint/d: 500
 * /ariac/arm2/arm/gains/linear_arm_actuator_joint/i: 0
 * /ariac/arm2/arm/gains/linear_arm_actuator_joint/i_clamp: 1
 * /ariac/arm2/arm/gains/linear_arm_actuator_joint/p: 10000
 * /ariac/arm2/arm/gains/shoulder_lift_joint/d: 150
 * /ariac/arm2/arm/gains/shoulder_lift_joint/i: 10
 * /ariac/arm2/arm/gains/shoulder_lift_joint/i_clamp: 50
 * /ariac/arm2/arm/gains/shoulder_lift_joint/p: 50000
 * /ariac/arm2/arm/gains/shoulder_pan_joint/d: 150
 * /ariac/arm2/arm/gains/shoulder_pan_joint/i: 0
 * /ariac/arm2/arm/gains/shoulder_pan_joint/i_clamp: 1
 * /ariac/arm2/arm/gains/shoulder_pan_joint/p: 10000
 * /ariac/arm2/arm/gains/wrist_1_joint/d: 5
 * /ariac/arm2/arm/gains/wrist_1_joint/i: 0
 * /ariac/arm2/arm/gains/wrist_1_joint/i_clamp: 1
 * /ariac/arm2/arm/gains/wrist_1_joint/p: 100
 * /ariac/arm2/arm/gains/wrist_2_joint/d: 2
 * /ariac/arm2/arm/gains/wrist_2_joint/i: 0
 * /ariac/arm2/arm/gains/wrist_2_joint/i_clamp: 1
 * /ariac/arm2/arm/gains/wrist_2_joint/p: 75
 * /ariac/arm2/arm/gains/wrist_3_joint/d: 1
 * /ariac/arm2/arm/gains/wrist_3_joint/i: 0
 * /ariac/arm2/arm/gains/wrist_3_joint/i_clamp: 1
 * /ariac/arm2/arm/gains/wrist_3_joint/p: 25
 * /ariac/arm2/arm/joints: ['linear_arm_actu...
 * /ariac/arm2/arm/state_publish_rate: 25
 * /ariac/arm2/arm/stop_trajectory_duration: 0.5
 * /ariac/arm2/arm/type: effort_controller...
 * /ariac/arm2/joint_state_controller/extra_joints: [{'position': 0.0...
 * /ariac/arm2/joint_state_controller/publish_rate: 50
 * /ariac/arm2/joint_state_controller/type: joint_state_contr...
 * /ariac/arm2/robot_description: <?xml version="1....
  * /ariac/arm2/robot_state_publisher/publish_frequency: 50.0
   * /ariac/arm2/robot_state_publisher/tf_prefix:
    * /ariac/arm2/tf_relay/frames: ['linear_arm_actu...
     * /ariac/arm2/tf_relay/prefix: arm2_
      * /gazebo/enable_ros_network: True
       * /rosdistro: melodic
        * /rosversion: 1.14.3
 * /sensors_description: <?xml version="1....
 * /sensors_tf_publisher/publish_frequency: 50.0
 * /sensors_tf_publisher/tf_prefix:
 * /use_sim_time: True

NODES
  /ariac/arm2/
    arm_controller_spawner (controller_manager/controller_manager)
    fake_joint_calibration (rostopic/rostopic)
    joint_state_controller_spawner (controller_manager/controller_manager)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    spawn_gazebo_model (gazebo_ros/spawn_model)
    tf_relay (osrf_gear/tf2_relay)
  /ariac/arm1/
    arm_controller_spawner (controller_manager/controller_manager)
    fake_joint_calibration (rostopic/rostopic)
    joint_state_controller_spawner (controller_manager/controller_manager)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    spawn_gazebo_model (gazebo_ros/spawn_model)
    tf_relay (osrf_gear/tf2_relay)
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_unpauser (osrf_gear/gazebo_unpauser.py)
    sensors_tf_publisher (robot_state_publisher/robot_state_publisher)
    spawn_gazebo_sensors (gazebo_ros/spawn_model)
    startup_ariac (osrf_gear/startup.sh)

ROS_MASTER_URI=http://localhost:11311

process[startup_ariac-1]: started with pid [2057]
Ensuring scoring log file exists
File doesn't exist - symlinking /root/.ariac/log/performance.log to /root/.gazebo/server-11345/default.log
^B[startup_ariac-1] process has finished cleanly
log file: /root/.ros/log/f3e0332a-4e17-11e9-aa44-0242ac110002/startup_ariac-1*.log
process[gazebo-2]: started with pid [2059]
zprocess[sensors_tf_publisher-3]: started with pid [2064]
process[spawn_gazebo_sensors-4]: started with pid [2104]
gzserver: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgazebo_common.so.9: undefined symbol: _ZN8ignition10fuel_tools12ClientConfig12SetUserAgentERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
================================================================================REQUIRED process [gazebo-2] has died!
process has died [pid 2059, exit code 127, cmd /opt/ros/melodic/lib/gazebo_ros/gzserver -u -e ode /tmp/ariac/gear.world __name:=gazebo __log:=/root/.ros/log/f3e0332a-4e17-11e9-aa44-0242ac110002/gazebo-2.log].
log file: /root/.ros/log/f3e0332a-4e17-11e9-aa44-0242ac110002/gazebo-2*.log
Initiating shutdown!
================================================================================
[ariac/arm2/tf_relay-5] killing on exit
[spawn_gazebo_sensors-4] killing on exit
[gazebo-2] killing on exit
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/gazebo_ros/spawn_model", line 26, in <module>
    from gazebo_ros import gazebo_interface
  File "/opt/ros/melodic/lib/python2.7/dist-packages/gazebo_ros/gazebo_interface.py", line 9, in <module>
    from gazebo_msgs.msg import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/gazebo_msgs/msg/__init__.py", line 1, in <module>
[sensors_tf_publisher-3] killing on exit
    from ._ContactState import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/gazebo_msgs/msg/_ContactState.py", line 8, in <module>
    import geometry_msgs.msg
  File "/opt/ros/melodic/lib/python2.7/dist-packages/geometry_msgs/msg/__init__.py", line 12, in <module>
    from ._Pose import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/geometry_msgs/msg/_Pose.py", line 2, in <module>
    """autogenerated by genpy from geometry_msgs/Pose.msg. Do not edit."""
KeyboardInterrupt
process[ariac/arm2/tf_relay-5]: started with pid [2111]
RLException: cannot add process [ariac/arm2/spawn_gazebo_model-6] after process monitor has been shut down
The traceback for the exception was written to the log file
================================================================================REQUIRED process [ariac_sim-1] has died!
process has died [pid 2030, exit code 1, cmd /opt/ros/melodic/lib/osrf_gear/gear.py --development-mode --no-gui --visualize-sensor-views -f /opt/ros/melodic/share/osrf_gear/config/sample.yaml /opt/ros/melodic/share/osrf_gear/config/sample_user_config.yaml __name:=ariac_sim __log:=/root/.ros/log/f3e0332a-4e17-11e9-aa44-0242ac110002/ariac_sim-1.log].
log file: /root/.ros/log/f3e0332a-4e17-11e9-aa44-0242ac110002/ariac_sim-1*.log
Initiating shutdown!
================================================================================
[ariac_sim-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by 130s** [comment]
As the instruction already gives a hint, the following fixed this.
```
sudo apt upgrade libignition-math4
```

**Comment by 130s** [comment]
Moved to https://github.com/130s/hut_ariac/issues/3
